#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
