#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get update
sudo apt-get install -y haproxy=2.8.\*
sudo chown -R $USER:$USER /etc/haproxy
sudo chown -R $USER:$USER /etc/default
chmod -R 755 /etc/haproxy/
chmod -R 755 /etc/default/
echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "frontend http
    bind *:80
    mode http
    default_backend web_backend

backend web_backend
   mode http
   balance roundrobin
   server 198265-web-01 52.91.202.237:80 check
   server 198265-web-02 34.224.16.163:80 check

" > /etc/haproxy/haproxy.cfg

sudo service haproxy start
