#!/usr/bin/env bash
# displays the content of the file /etc/passwd.
# script should only display:
# username
# user id
# Home directory path for the user

while read test;
do
echo "$test" | cut -d ":" -f1,3,6
done < "/etc/passwd"
